# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofcloud', '0015_instance_parallelisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='decomposition',
            field=models.TextField(blank=True),
        ),
    ]
